export type Currency = { code: string; name: string; symbol: string };
export type CurrencySection = { region: string; currencies: Currency[] };

export const CURRENCY_SECTIONS: CurrencySection[] = [
  {
    region: "Global",
    currencies: [
      { code: "AUD", name: "Australian Dollar", symbol: "A$" },
      { code: "CAD", name: "Canadian Dollar", symbol: "CA$" },
      { code: "CHF", name: "Swiss Franc", symbol: "CHF" },
      { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
      { code: "DKK", name: "Danish Krone", symbol: "kr" },
      { code: "EUR", name: "Euro", symbol: "€" },
      { code: "GBP", name: "British Pound", symbol: "£" },
      { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
      { code: "JPY", name: "Japanese Yen", symbol: "¥" },
      { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
      { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
      { code: "SEK", name: "Swedish Krona", symbol: "kr" },
      { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
      { code: "USD", name: "US Dollar", symbol: "$" },
    ],
  },
  {
    region: "Asia & Middle East",
    currencies: [
      { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
      { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
      { code: "BHD", name: "Bahraini Dinar", symbol: "BD" },
      { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
      { code: "ILS", name: "Israeli Shekel", symbol: "₪" },
      { code: "INR", name: "Indian Rupee", symbol: "₹" },
      { code: "KRW", name: "South Korean Won", symbol: "₩" },
      { code: "KWD", name: "Kuwaiti Dinar", symbol: "KD" },
      { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs" },
      { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
      { code: "OMR", name: "Omani Rial", symbol: "ر.ع." },
      { code: "PHP", name: "Philippine Peso", symbol: "₱" },
      { code: "PKR", name: "Pakistani Rupee", symbol: "Rs" },
      { code: "QAR", name: "Qatari Riyal", symbol: "ر.ق" },
      { code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
      { code: "THB", name: "Thai Baht", symbol: "฿" },
      { code: "TRY", name: "Turkish Lira", symbol: "₺" },
      { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
    ],
  },
  {
    region: "Americas",
    currencies: [
      { code: "ARS", name: "Argentine Peso", symbol: "$" },
      { code: "BRL", name: "Brazilian Real", symbol: "R$" },
      { code: "CLP", name: "Chilean Peso", symbol: "CLP$" },
      { code: "COP", name: "Colombian Peso", symbol: "COL$" },
      { code: "MXN", name: "Mexican Peso", symbol: "MX$" },
      { code: "PEN", name: "Peruvian Sol", symbol: "S/" },
    ],
  },
  {
    region: "Europe",
    currencies: [
      { code: "CZK", name: "Czech Koruna", symbol: "Kč" },
      { code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
      { code: "PLN", name: "Polish Zloty", symbol: "zł" },
      { code: "RON", name: "Romanian Leu", symbol: "lei" },
      { code: "RUB", name: "Russian Ruble", symbol: "₽" },
      { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
    ],
  },
  {
    region: "Africa — West",
    currencies: [
      { code: "CVE", name: "Cape Verdean Escudo", symbol: "$" },
      { code: "GMD", name: "Gambian Dalasi", symbol: "D" },
      { code: "GHS", name: "Ghanaian Cedi", symbol: "₵" },
      { code: "GNF", name: "Guinean Franc", symbol: "FG" },
      { code: "LRD", name: "Liberian Dollar", symbol: "L$" },
      { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM" },
      { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
      { code: "SLL", name: "Sierra Leonean Leone", symbol: "Le" },
      { code: "XOF", name: "West African CFA Franc", symbol: "CFA" },
    ],
  },
  {
    region: "Africa — East",
    currencies: [
      { code: "BIF", name: "Burundian Franc", symbol: "Fr" },
      { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj" },
      { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk" },
      { code: "ETB", name: "Ethiopian Birr", symbol: "Br" },
      { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
      { code: "KMF", name: "Comorian Franc", symbol: "CF" },
      { code: "MGA", name: "Malagasy Ariary", symbol: "Ar" },
      { code: "MUR", name: "Mauritian Rupee", symbol: "₨" },
      { code: "RWF", name: "Rwandan Franc", symbol: "RF" },
      { code: "SCR", name: "Seychellois Rupee", symbol: "₨" },
      { code: "SOS", name: "Somali Shilling", symbol: "Sh" },
      { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh" },
      { code: "UGX", name: "Ugandan Shilling", symbol: "USh" },
    ],
  },
  {
    region: "Africa — Southern",
    currencies: [
      { code: "AOA", name: "Angolan Kwanza", symbol: "Kz" },
      { code: "BWP", name: "Botswana Pula", symbol: "P" },
      { code: "LSL", name: "Lesotho Loti", symbol: "L" },
      { code: "MOZ", name: "Mozambican Metical", symbol: "MT" },
      { code: "MWK", name: "Malawian Kwacha", symbol: "MK" },
      { code: "NAD", name: "Namibian Dollar", symbol: "N$" },
      { code: "SZL", name: "Swazi Lilangeni", symbol: "L" },
      { code: "ZAR", name: "South African Rand", symbol: "R" },
      { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK" },
      { code: "ZWL", name: "Zimbabwean Dollar", symbol: "Z$" },
    ],
  },
  {
    region: "Africa — Central",
    currencies: [
      { code: "CDF", name: "Congolese Franc", symbol: "FC" },
      { code: "STN", name: "São Tomé & Príncipe Dobra", symbol: "Db" },
      { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA" },
    ],
  },
  {
    region: "Africa — North",
    currencies: [
      { code: "DZD", name: "Algerian Dinar", symbol: "دج" },
      { code: "EGP", name: "Egyptian Pound", symbol: "E£" },
      { code: "LYD", name: "Libyan Dinar", symbol: "LD" },
      { code: "MAD", name: "Moroccan Dirham", symbol: "MAD" },
      { code: "SDG", name: "Sudanese Pound", symbol: "ج.س." },
      { code: "TND", name: "Tunisian Dinar", symbol: "د.ت" },
    ],
  },
];

export const CURRENCIES: Currency[] = CURRENCY_SECTIONS.flatMap((s) => s.currencies);
